# Generated by Django 3.1.2 on 2020-10-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10)),
                ('posi', models.CharField(max_length=10)),
                ('card', models.CharField(max_length=1)),
                ('action', models.CharField(max_length=10)),
                ('tokuten', models.IntegerField()),
                ('turn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10)),
                ('turn', models.IntegerField()),
                ('tokuten', models.IntegerField()),
                ('deck', models.CharField(max_length=50)),
            ],
        ),
    ]
