# Generated by Django 3.1.2 on 2020-12-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='deck',
            field=models.CharField(max_length=100),
        ),
    ]
