# Generated by Django 3.1.2 on 2020-12-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0002_auto_20201202_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='bot_deck',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
