# Generated by Django 3.1.2 on 2020-12-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0004_auto_20201215_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionhistory',
            name='condition',
            field=models.CharField(default='a', max_length=10),
            preserve_default=False,
        ),
    ]
